"""Add comparrison table

Revision ID: 153415849c0a
Revises: 
Create Date: 2025-08-21 12:06:53.453326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '153415849c0a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comparisons',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('before_image', sa.String(), nullable=False),
    sa.Column('after_image', sa.String(), nullable=False),
    sa.Column('diff_image', sa.String(), nullable=False),
    sa.Column('pixel_difference', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('after_image'),
    sa.UniqueConstraint('before_image'),
    sa.UniqueConstraint('diff_image')
    )
    op.create_index(op.f('ix_comparisons_id'), 'comparisons', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comparisons_id'), table_name='comparisons')
    op.drop_table('comparisons')
    # ### end Alembic commands ###
